name: .NET Core

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reportgenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.7.1
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - name: Generate Reports
        run: reportgenerator -reports:./Tests/**/coverage.cobertura.xml -targetdir:coverlet/reports -reporttypes:"Cobertura"
      - uses: 5monkeys/cobertura-action@master
        name: Publish Code Coverage
        with:
          path: 'coverlet/reports/Cobertura.xml'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 0
